[Leo] Add hexadecimal, octal, binary numerals.
ProvableHQ/grammars pull request #70
Opened 2024-10-21 16:24 UTC by acoglio

This passes all the usual ACL2 checks.

2024-10-21 17:22 UTC, bendyarm commented on leo.abnf
> +octal-numeral = 1*( octal-digit *"_" )
```suggestion
"0o" 1*( octal-digit *"_" )
```

2024-10-21 17:22 UTC, bendyarm commented on leo.abnf
> +binary-numeral = 1*( binary-digit *"_" )
```suggestion
binary-numeral = "0b" 1*( binary-digit *"_" )
```

2024-10-21 17:24 UTC, bendyarm commented on leo.abnf
> +hexadecimal-numeral = 1*( hexadecimal-digit *"_" )
```suggestion
hexadecimal-numeral = "0x" 1*( hexadecimal-digit *"_" )
```

2024-10-21 17:36 UTC, bendyarm requested changes
Added some suggested changes.
Also we should think more about how to handle negative literals such as i8
other than field/group/scalar.
If we are handling then as unary minus operator, it looks to me like the grammar doesn't support that.

2024-10-21 18:57 UTC, acoglio commented
Group coordinates are still in use.

2024-10-21 23:08 UTC, bendyarm commented on leo.abnf
Probably
```
cast-expression = unary-expression %s"as" named-primitive-type
```
should be changed to
```
cast-expression = unary-expression
                / unary-expression %s"as" named-primitive-type
```

2024-10-22 00:44 UTC, acoglio commented on leo.abnf
Yes, there is a missing case in that rule. Great catch!

2024-10-22 04:01 UTC, bendyarm approved these changes
Looks good!

2024-10-22 16:09 UTC, acoglio commented on leo.abnf
> +cast-expression = unary-expression
Yes, an oversight indeed. It was not following the same hierarchical pattern as the other kinds of expressions.

2024-11-01 16:49 UTC, d0cd approved these changes
LGTM!

2024-11-01 16:51 UTC, merged